version: 0.2

env:
  secrets-manager:
    AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
    AWS_DEFAULT_REGION: "AWS_DEFAULT_REGION"
    ACC_ID: "ACC_ID"
    ECR_REPO_URI: "ECR_REPO_URI"
    CLUSTER_NAME: "CLUSTER_NAME"
    DOCKER_LOGIN: "DOCKER_LOGIN"
    
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - cd app
      - npm install
      - cd ..
      - sudo yum install docker -y
      - sudo yum install gettext -y
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.15/2023-01-11/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

  pre_build:
    commands:
      - echo Pre-build steps...
      - export AWS_ACCESS_KEY_ID=$(aws secretsmanager get-secret-value --secret-id $AWS_ACCESS_KEY_ID --region $AWS_DEFAULT_REGION --query SecretString --output text | jq -r .AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(aws secretsmanager get-secret-value --secret-id $AWS_SECRET_ACCESS_KEY --region $AWS_DEFAULT_REGION --query SecretString --output text | jq -r .SecretAccessKey)
      - export AWS_DEFAULT_REGION=$(aws secretsmanager get-secret-value --secret-id $AWS_DEFAULT_REGION --region $AWS_DEFAULT_REGION --query SecretString --output text | jq -r .region)
      - export ECR_REPO_URI=$(aws secretsmanager get-secret-value --secret-id $ECR_REPO_URI --region $AWS_DEFAULT_REGION --query SecretString --output text | jq -r .ECR_REPO_URI)
      - export DOCKER_LOGIN=$(aws secretsmanager get-secret-value --secret-id $DOCKER_LOGIN --region $AWS_DEFAULT_REGION --query SecretString --output text | jq -r .DOCKER_LOGIN)
      - echo "------ Logging into the ECR repo ------"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REPO_URI}

  build:
    commands:
      - echo Build started on `date`
      - cd app
      - npm run build
      - cd ..
      - echo Building Docker image...
      - docker login -u ahmed7860 -p ${DOCKER_LOGIN}
      - docker build -t my-app:latest ./app   # Assuming Dockerfile is in the root of 'app' directory
      - echo Tagging Docker image...
      - docker tag my-app:latest ${ECR_REPO_URI}:${CODEBUILD_BUILD_NUMBER}
      - docker tag my-app:latest ${ECR_REPO_URI}:latest
      - echo Pushing Docker image to ECR...
      - docker push ${ECR_REPO_URI}:${CODEBUILD_BUILD_NUMBER}
      - docker push ${ECR_REPO_URI}:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to EKS...
      - aws eks update-kubeconfig --name ${CLUSTER_NAME} --region ${AWS_DEFAULT_REGION}
      - echo Writing image definitions file...
      - printf '[{"name":"app","imageUri":"%s"}]' ${ECR_REPO_URI}:${CODEBUILD_BUILD_NUMBER} > imagedefinitions.json
      - echo Changing the deployment.yaml file values...
      - envsubst < deployment.yaml.tmp > deployment.yaml
      - echo Applying the manifest files...
      - kubectl apply -f mongo-deployment.yaml
      - kubectl apply -f deployment.yaml

artifacts:
  files:
    - imagedefinitions.json
    - '**/*'
